### ISSUE TITLE
undefined method `id' for nil:NilClass

### ISSUE THREAD

**Issue by nishantpant** [thirst/glass-rails#14]
Hi, 

I am a Rails noob so it could be that I am missing something basic. But I followed every single step of your instructions, but keep getting this error :

ERROR -->undefined method `id' for nil:NilClass

LINE OF CODE --> gt = Glass::Tweet.new(google_account_id: GoogleAccount.first.id)

**Comment by logicalhan** [comment]
I think you may not actually have a google authenticated account in your database.

What does GoogleAccount.first return?

**Comment by nishantpant** [comment]
It returns nil. And I checked in RAILS CONSOLE GoogleAccount table is empty. The question is how does it get populated....I am a little confused. Does the gem take care of oauth or do I have to take care of that part? If I have to take care of it, then that explains why it is empty. For some reason, I thought the gem takes care of auth and posting at the same time. 

Thanks for your super quick reply !!!

**Comment by nishantpant** [comment]
Maybe this error message helps.

-Thanks again
Nishant

NoMethodError in TimelineController#send_message1
undefined method `id' for nil:NilClass
Extracted source (around line _#32_):

303132333435

  def send_message1
    gt = Glass::Tweet.new(google_account_id: GoogleAccount.first.id)
    gt.serialize({template_variables: {content: "random stuff"}})
    gt.mirror_insert()
  end

Rails.root: /vagrant/glass-app

**Comment by logicalhan** [comment]
you have to do the google authentication piece yourself, since that's not really reason for this library. once you do the google authentication piece, (which you can do via omniauth) then you should be able to populate your google account table with the proper credentials and use this gem.
