### ISSUE TITLE
Move OAuth config from YML to ENV

### ISSUE THREAD

**Issue by kurtisnelson** [thirst/glass-rails#4]
The OAuth secrets should be loaded from ENV so that they are not floating around in the repository and can easily be set with other things between environments such as heroku.
I've thrown it together at kurtisnelson/glass-rails@be245ed55dea252f079307cef9b52ebfcb630144

**Comment by logicalhan** [comment]
commit e6bb80bd3fdc8c73d936589bfbc12fe6d94ee20a fixes this.
